#!/usr/bin/env python3
"""Backfills fintech/archive/ and security/archive/ with historical dated
briefings, reusing the bot's current index.html as the structural template
(header-row + calendar-picker, no FAB, keyword-only trend summaries) and
injecting each historical date's actual news content (the 3-screen pager
block) from the original source file.

Source: C:\\Users\\Administrator\\workspace\\ai pm-workshop1\\study-output\\industry

Run:
    python scripts/build_archive_from_source.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(r"C:\Users\Administrator\workspace\ai pm-workshop1\study-output\industry")

EARLIEST = "2026-07-23"
LATEST = "2026-08-08"

TOPICS = [
    {
        "key": "fintech",
        "dir": "fintech",
        "title": "핀테크·토큰증권 뉴스 브리핑",
        "src_glob": "fintech-token-news-*.html",
        "src_dir": SRC,
        "extra": {"2026-07-24": SRC / "2026-07-24.html"},
    },
    {
        "key": "security",
        "dir": "security",
        "title": "정보보안 뉴스 브리핑",
        "src_glob": "information-security-news-*.html",
        "src_dir": SRC / "정보보안",
        "extra": {},
    },
]

PAGER_RE = re.compile(
    r'(<div class="pager" id="pager">\n\n)(.*?)(\n  </div>\n\n  <div class="dots">)',
    re.DOTALL,
)
TREND_TEXT_RE = re.compile(
    r'\n        <div class="trend-summary-text">\n.*?\n        </div>',
    re.DOTALL,
)
TITLE_RE = re.compile(r"<title>.*?</title>")
DATEPICKER_RE = re.compile(r'<input type="date" id="datePicker"[^>]*>')
PAGE_H1_RE = re.compile(r'<h1 class="page-title">(.*?)</h1>')


def extract_page_title(template: str) -> str:
    match = PAGE_H1_RE.search(template)
    if not match:
        raise ValueError("page-title h1 not found in template")
    return match.group(1)


def extract_pager_content(html: str) -> str:
    match = PAGER_RE.search(html)
    if not match:
        raise ValueError("pager block not found")
    content = match.group(2)
    content = TREND_TEXT_RE.sub("", content)
    return content


def build_file(template: str, topic_title: str, date: str, pager_content: str) -> str:
    out = TITLE_RE.sub(f"<title>{topic_title} - {date.replace('-', '.')}</title>", template, count=1)
    out = DATEPICKER_RE.sub(
        f'<input type="date" id="datePicker" min="{EARLIEST}" max="{LATEST}" value="{date}" aria-label="날짜별로 보기">',
        out,
        count=1,
    )
    out = PAGER_RE.sub(lambda m: m.group(1) + pager_content + m.group(3), out, count=1)
    return out


def main():
    for topic in TOPICS:
        template_path = ROOT / topic["dir"] / "index.html"
        template = template_path.read_text(encoding="utf-8")
        page_title = extract_page_title(template)

        archive_dir = ROOT / topic["dir"] / "archive"
        archive_dir.mkdir(parents=True, exist_ok=True)

        sources = {}
        for f in sorted(topic["src_dir"].glob(topic["src_glob"])):
            m = re.search(r"(\d{4}-\d{2}-\d{2})\.html$", f.name)
            if m:
                sources[m.group(1)] = f
        sources.update(topic["extra"])

        for date, src_path in sorted(sources.items()):
            if date == LATEST:
                continue  # already present in archive/, generated by the bot itself
            old_html = src_path.read_text(encoding="utf-8")
            pager_content = extract_pager_content(old_html)
            new_html = build_file(template, page_title, date, pager_content)
            out_path = archive_dir / f"{date}.html"
            out_path.write_text(new_html, encoding="utf-8")
            print(f"wrote {topic['dir']}/archive/{date}.html")

        # widen today's date-picker range now that history exists
        for p in (template_path, archive_dir / f"{LATEST}.html"):
            if p.exists():
                text = p.read_text(encoding="utf-8")
                text = DATEPICKER_RE.sub(
                    f'<input type="date" id="datePicker" min="{EARLIEST}" max="{LATEST}" value="{LATEST}" aria-label="날짜별로 보기">',
                    text,
                    count=1,
                )
                p.write_text(text, encoding="utf-8")
                print(f"widened date range in {p.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
